name: Xlog

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Allow non-ASCII character
        run: git config core.quotepath false

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Install xlog
        env:
          XLOG_VERSION: v1.7.8
        run: curl --location https://github.com/emad-elsaid/xlog/releases/download/${XLOG_VERSION}/xlog-${XLOG_VERSION}-linux-amd64.tar.gz | tar -xz -C ..

      - name: Build
        run: |
          ../xlog \
          --build . \
          --sitename="Noureldin" \
          --theme="dark" \
          --codestyle="catppuccin-latte" \
          --index=home \
          --custom.head=header.html \
          --sitemap.domain=nmn3m.github.io \
          --activitypub.domain=nmn3m.github.io \
          --activitypub.username=nour \
          --activitypub.summary="A DevOps Engineer." \
          --og.domain=nmn3m.github.io \
          --twitter.username=@nmn3m \
          --github.url=https://github.com/nmn3m/nmn3m.github.io/edit/main \
          --rss.domain=nmn3m.github.io \
          --rss.description="A DevOps Engineer"
          rm *.md
          chmod -R 0777 .

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4